# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a695370fea96433bc41b73ac65e9f1d036f1e3b3a2b4aaecc9cc026bfdfdf012f87eaf63bdded5d749c8fd2e828e7a8e17e48d4f073fef034e6b5ebf721a64e8

test:
  secret_key_base: ee4908a6e85f600f88aeeaacd63347bbd5e4038b872d3c71fe504efa628541c39f8fd538767c2cf6227044eb1fd30297b4d71d7431b5e05598668e808e8da535

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
